=== alumnoangel/XML-Repo/Editorial/editorial.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ediciones_aranda">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="cabecera">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="titulo" type="xs:string" />
							<xs:element name="contenido" type="xs:string" />
							<xs:element name="descripcion" type="xs:string" />
							<xs:element name="fecha" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="tabla">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="region">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="sur">
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" name="trim" type="xs:integer" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element maxOccurs="unbounded" name="centro">
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" name="trim" type="xs:integer" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element maxOccurs="unbounded" name="norte">
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" name="trim" type="xs:integer" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="trimestre" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== alumnoangel/XML-Repo/Editorial/editorial_X.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<ediciones_aranda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:noNamespaceSchemaLocation="editorial.xsd">

  <cabecera>
    <titulo>Ediciones Aranda</titulo>
    <contenido>Informe regional del ventas</contenido>
    <descripcion>Descripcion: informe de ventas para las regiones Norte, Centro y Sur</descripcion>
    <fecha>Fecha: 30/12/2009</fecha>
  </cabecera>
  <tabla>
    <region>
      <norte>Norte
        <trim>1</trim>
         ventas>24000 ventas>
        <trim>2</trim>
         ventas>38600 ventas>
        <trim>3</trim>
         ventas> ventas>
        <trim>4</trim>
         ventas> ventas>
      </norte>
    </region>
    <region>
      <centro>Centro
        <trim>1</trim>
         ventas> ventas>
        <trim>2</trim>
         ventas>16080 ventas>
        <trim>3</trim>
         ventas>25000 ventas>
        <trim>4</trim>
         ventas>29000 ventas>
      </centro>
    </region>
    <region>
      <sur>Sur
        <trim>1</trim>
         ventas>27000 ventas>
        <trim>2</trim>
         ventas>31400 ventas>
        <trim>3</trim>
         ventas>40100 ventas>
        <trim>4</trim>
         ventas>30000 ventas>
      </sur>
    </region>
    <trimestre>Trimestre</trimestre>
   ventasros_vendido ventasros vendidos libros_vendidos>
  </tabla>
</ediciones_aranda>
