=== alumnoangel/XML-Repo/Libreria/Libreria.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Libreria">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="libro">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="autores">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="autor">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="ape1" type="xs:string" />
													<xs:element name="ape2" type="xs:string" />
													<xs:element name="nombre" type="xs:string" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="titulo" type="xs:string" />
							<xs:element name="codigoLibro" type="xs:integer" />
							<xs:element name="editorial" type="xs:string" />
							<xs:element name="edicion" type="xs:integer" />
							<xs:element name="f.publicacion" type="xs:integer" />
							<xs:element name="ISBN" type="xs:integer" />
							<xs:element name="numeroPaginas" type="xs:integer" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== alumnoangel/XML-Repo/Libreria/Libreria_X.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<Libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Libreria.xsd">
    <libro>
        <autores>
            <autor>
                <ape1>Perez</ape1>
                <ape2>Rubalcaba</ape2>
                <nombre>Alfonso</nombre>
            </autor>
            <autor>
                <ape1></ape1>
                <ape2></ape2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>2 + 2 son 25</titulo>
        <codigoLibro>5894</codigoLibro>
        <editorial>Planeta</editorial>
        <edicion>5</edicion>
        <f.publicacion>2009</f.publicacion>
        <ISBN>12365</ISBN>
        <numeroPaginas>98</numeroPaginas>
    </libro>
    <libro>
        <autores>
            <autor>
                <ape1>Zapatero</ape1>
                <ape2>Rodriguez</ape2>
                <nombre>Joselito</nombre>
            </autor>
            <autor>
                <ape1></ape1>
                <ape2></ape2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>Los tres cerditos</titulo>
        <codigoLibro>5494</codigoLibro>
        <editorial>La casa de la abuel</editorial>
        <edicion>1</edicion>
        <f.publicacion>1314</f.publicacion>
        <ISBN>65432</ISBN>
        <numeroPaginas>312</numeroPaginas>
    </libro>
    <libro>
        <autores>
            <autor>
                <ape1>Rajoy</ape1>
                <ape2>Perez</ape2>
                <nombre>Mario</nombre>
            </autor>
            <autor>
                <ape1></ape1>
                <ape2></ape2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>Alí Baba</titulo>
        <codigoLibro>5891</codigoLibro>
        <editorial>Planeta</editorial>
        <edicion>4</edicion>
        <f.publicacion>2014</f.publicacion>
        <ISBN>65432</ISBN>
        <numeroPaginas>201</numeroPaginas>
    </libro>
    <libro>
        <autores>
            <autor>
                <ape1>Sanchez</ape1>
                <ape2>Iglesias</ape2>
                <nombre>Perico</nombre>
            </autor>
            <autor>
                <ape1></ape1>
                <ape2></ape2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>Donde dije digo digo Diego</titulo>
        <codigoLibro>7894</codigoLibro>
        <editorial>Versache</editorial>
        <edicion>5</edicion>
        <f.publicacion>2020</f.publicacion>
        <ISBN>55432</ISBN>
        <numeroPaginas>138</numeroPaginas>
    </libro>
    <libro>
        <autores>
            <autor>
                <ape1>Cifuentes</ape1>
                <ape2>Rubalcaba</ape2>
                <nombre>Cristina</nombre>
            </autor>
            <autor>
                <ape1></ape1>
                <ape2></ape2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>La algarroba</titulo>
        <codigoLibro>5194</codigoLibro>
        <editorial>Planeta</editorial>
        <edicion>2</edicion>
        <f.publicacion>2015</f.publicacion>
        <ISBN>59843</ISBN>
        <numeroPaginas>222</numeroPaginas>
    </libro>
    <libro>
        <autores>
            <autor>
                <ape1>Jimenez</ape1>
                <ape2>Rueda</ape2>
                <nombre>Miguel</nombre>
            </autor>
            <autor>
                <ape1>Santaella</ape1>
                <ape2>Perales</ape2>
                <nombre>Juana María</nombre>
            </autor>
        </autores>
        <titulo>Entre dos mundos</titulo>
        <codigoLibro>5890</codigoLibro>
        <editorial>Los Remedios</editorial>
        <edicion>2</edicion>
        <f.publicacion>1999</f.publicacion>
        <ISBN>894711</ISBN>
        <numeroPaginas>201</numeroPaginas>
    </libro>
    <libro>
        <autores>
            <autor>
                <ape1>Casillas</ape1>
                <ape2>Bernabeu</ape2>
                <nombre>Monica</nombre>
            </autor>
            <autor>
                <ape1></ape1>
                <ape2></ape2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>La vida en blanco</titulo>
        <codigoLibro>589</codigoLibro>
        <editorial>Alminares</editorial>
        <edicion>5</edicion>
        <f.publicacion>2020</f.publicacion>
        <ISBN>354482</ISBN>
        <numeroPaginas>144</numeroPaginas>
    </libro>
    <libro>
        <autores>
            <autor>
                <ape1>Roger</ape1>
                <ape2>Correia</ape2>
                <nombre>David</nombre>
            </autor>
            <autor>
                <ape1>Flores</ape1>
                <ape2>Cabrerizo</ape2>
                <nombre>Almudena</nombre>
            </autor>
        </autores>
        <titulo>En boca de todos</titulo>
        <codigoLibro>594</codigoLibro>
        <editorial>Planeta</editorial>
        <edicion>3</edicion>
        <f.publicacion>2018</f.publicacion>
        <ISBN>2555414</ISBN>
        <numeroPaginas>156</numeroPaginas>
    </libro>
    <libro>
        <autores>
            <autor>
                <ape1>Galdeano</ape1>
                <ape2>Rodriguez</ape2>
                <nombre>Aitor</nombre>
            </autor>
            <autor>
                <ape1></ape1>
                <ape2></ape2>
                <nombre></nombre>
            </autor>
        </autores>
        <titulo>El silencio de mi mente</titulo>
        <codigoLibro>54194</codigoLibro>
        <editorial>Gaca</editorial>
        <edicion>1</edicion>
        <f.publicacion>2003</f.publicacion>
        <ISBN>6555210</ISBN>
        <numeroPaginas>89</numeroPaginas>
    </libro>
    <libro>
        <autores>
            <autor>
                <ape1>Del Cerro</ape1>
                <ape2>Jimenez</ape2>
                <nombre>Pablo</nombre>
            </autor>
            <autor>
                <ape1>Jardon</ape1>
                <ape2>Menendez</ape2>
                <nombre>Alberto</nombre>
            </autor>
        </autores>
        <titulo>Campo de sueños</titulo>
        <codigoLibro>5004</codigoLibro>
        <editorial>Alminares</editorial>
        <edicion>1</edicion>
        <f.publicacion>2010</f.publicacion>
        <ISBN>26591</ISBN>
        <numeroPaginas>199</numeroPaginas>
    </libro>
</Libreria>
