=== alumnoangel/XML-Repo/Clientes/clientes.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT clientes (sede)*>

<!ELEMENT sede (codSede|empleado|fechaAlta|descripcion|direccion|cliente)>

<!ELEMENT cliente (codCliente|numeroViviendas|coste|resumen|plazo)*>

<!ELEMENT codCliente ANY>

<!ELEMENT numeroViviendas (#PCDATA)>

<!ELEMENT coste (#PCDATA)>

<!ELEMENT resumen (#PCDATA)>

<!ELEMENT plazo (CDATA)>

<!ELEMENT codSede ANY>

<!ELEMENT empleado (#PCDATA)>

<!ELEMENT fechaAlta (CDATA)>

<!ELEMENT descripcion (#PCDATA)>
    <!ATTLIST descripcion (solvente|insolvente)>

<!ELEMENT direccion (#PCDATA)>

=== alumnoangel/XML-Repo/Clientes/Clientes_D.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE clientes SYSTEM "clientes.dtd">
<clientes>
    <sede codigo="W1385400">
        <direccion>calle falsa numero 123</direccion>
        <direccion>calle falsa numero 321</direccion>
        <empleado>Juan Carmona</empleado>
        <fechaAlta>10-15-2020</fechaAlta>
        <descripcion>solvente</descripcion>
        <cliente codigo="AAA-548">
            <numeroViviendas>1</numeroViviendas>
            <coste>50000</coste>
            <resumen>vivienda de tres habitaciones</resumen>
            <plazo>16-11-2022</plazo>
        </cliente>
    </sede>
</clientes>
